export const CELLS_AVAILABLE_REQUEST = 'CELLS_AVAILABLE_REQUEST'
export const GET_AVAILABLE_CELLS = 'GET_AVAILABLE_CELLS'
export const GET_CELLS_ERROR = 'GET_CELLS_ERROR'

export const UID_REQUEST = 'UID_REQUEST'
export const SET_UID = 'SET_UID'
export const GET_UID_ERROR = 'GET_UID_ERROR'
